# Generated by Django 3.2.19 on 2023-07-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('memo', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to=None)),
                ('date', models.DateField()),
            ],
        ),
    ]
