# Generated by Django 4.2.3 on 2023-07-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='memo',
            field=models.TextField(),
        ),
    ]
